resources:
  - url: http://127.0.0.1:5000/big-slider-card.js
    type: module
views:
  - cards:
      - type: custom:google-slider-card
        name: Google Slider Card Development
        entity: light.sun
        test_gui: true
      - type: custom:google-button-card
        name: Google Button Card Development
        entity: sun.sun
        test_gui: true
